# Generated by Django 4.2.3 on 2023-07-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='user',
        ),
    ]
